config/routes.rb
Rails.application.routes.draw do

match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

resources :password_resets, only: [:new, :create, :edit, :update]

  get "/home" => "welcome#index"

  get "/about" => "welcome#about", as: :about_us

  root "welcome#index"

  get "/contact_us" => "contact_us#new"
  post "/contact_us" => "contact_us#create"

  resources :users, only: [:new, :create]

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  resources :questions do

    resources :answers, only: [:create, :destroy, :edit, :update]
    resources :likes, only: [:create, :destroy]
    resources :votes, only: [:create, :update, :destroy]
    resources :insights, only: [:create]
  end

get "/questions" => "questions#index"

end

app/models/question.rb
class Question < ActiveRecord::Base

  #when using 'has_many' you must put a symbol for the associated record in plural format
  #you also should provide the :dependent option which can be either:
  # :destroy - which deletes all the associated answers when the question is deleted
  # :nullify - which makes "question_id" NULL for all associated answers
  has_many :answers, dependent: :destroy
  has_many :insights, dependent: :destroy
  belongs_to :category
  belongs_to :user

  has_many :likes, dependent: :destroy
  has_many :liking_users, through: :likes, source: :user

  has_many :votes, dependent: :destroy
  has_many :voting_users, through: :votes, source: :user

  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings

  validates(:title, {presence: true, uniqueness: {message: "Must be unique!"}})
  validates :body, length: {minimum: 5}
  validates :view_count, numericality: {greater_than_or_equal_to: 0}


  # VALID_EMAIL_REGEX = /\A([\w+\-]\.?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
    # validates :email, format: VALID_EMAIL_REGEX

    # this validates that the combination of title and body must be unique
    # it means that title by itself doesn't have to unique and body by itslef
    # doesn't have to be unique but the combination of the two must be unique
    # validates :title, uniqueness: {scope: :body}

  # validates :title, uniqueness: {scope: :body}

  #validateS are for built in validations
  #validate (without s, is for custom ones)


#This below is a custom validation
  validate :no_monkey



#This will call the 'set_defaults' method right after the initialize phase
after_initialize :set_defaults
before_validation :titelize_title

extend FriendlyId
friendly_id :title, use: :history

mount_uploader :image, ImageUploader

def self.recent_three
  order("created_at DESC").limit(3)
end

def self.search_titles_and_body(search_string)
  where(["title ILIKE ? OR body ILIKE ?", "%#{search_string}%", "%#{search_string}%"])
  # where(["title ILIKE :term OR body ILIKE :term", {term: "%#{search_string}%"}])
end

#alternatively you can do the above via a lambda
# scope :recent_three, lambda {order("created_at DESC").limit(3)}


  def user_full_name
    user ? user.full_name : ""
  end

  def like_for(user)
    likes.find_by_user_id user if user
  end

  def vote_for(user)
    votes.find_by_user_id user if user
  end

  def vote_value
    votes.up_count - votes.down_count
  end



  # simple alternative to friendly id
  # def to_param
  #   "#{id}-#{title}".parameterize
  # end


#set it as private as no need external axs from the console
  private

  def titelize_title
    self.title = title.titleize
  end

  def set_defaults
    self.view_count ||= 0
  end

  def no_monkey
    if title.present? && title.downcase.include?("monkey")
      errors.add(:title, "No monkeys!")
    end
  end


end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < ApplicationController

  def index
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

before_action :authenticate_user!, except: [:index, :show]
#Defining a method as a before action will make it so that rails executes that method before executing the action. This is still within the same request cycle
#You can give the before action method 2 options; :only or :except this will help you limit the action which the find_question method will be executed before
#In this case, before action will only be executed before show edit update and destroy actions.
before_action :find_question, only: [:show, :edit, :update, :destroy]
before_action :authorize_question, only: [:edit, :update, :destroy]

# include QuestionsAnswersHelper
#   helper_method :user_like

  def create
    #method one
    # @question = Question.new
    # @question.title = params[:question][:title]
    # @question.body = params[:question][:body]
    # @question.save

    #method two
    # @question = Question.create({ title: params[:question][:title],
    #                               body: params[:question][:body]})

    # method three
    # @question = Question.create(params[:question])
    # #This will throw a: ActiveModel::ForbiddenAttributesError exception

    # method four Strong Parameters

    @question       = Question.new(question_params)
    @question.user  = current_user
    if @question.save
      flash[:notice] = "Question created!"
      #to change the url and display the page we do
      # Method 1 to do this is redirect_to question_path({id: @question.id})
      # Method 2 a bit simpler
      redirect_to question_path(@question)
    else
      flash.now[:alert] = "Question didn't save!"
      #if the db save fails, it renders the apps/views/questions/new.html.erb because the default in this action is to render app/views/qeuestionscreate.html.erb
      render :new
    end


  end


  #WE receive a request such as : GET /questions/56
  #params[:id] will be '56'
  def show
    @answer = Answer.new
    @list_of_voting_users ||= @question.votes.joins(:user).pluck("users.first_name").join(" ")
    @list_of_liked_users ||= @question.likes.joins(:user).pluck("users.first_name").join(" ")
    respond_to do |format|
      format.html { render }
      format.json { render json: {question: @question, insights: @question.insights.order(created_at: :desc) } }
      format.xml { render xml: @question.to_xml }
    end
  end


  def new
    # WE define a new "Question" object in order to be able to properly generate a form in Rails
    @question = Question.new
  end

  def index
    @questions = Question.all
    respond_to do |format|
      format.html { render }
      format.json { render json: @questions.select(:id, :title, :view_count) }
    end
  end

  def edit
  end

  def update
    @question.slug = nil
    if @question.update question_params
      redirect_to question_path(@question), notice: "Question updated!"
    else
      flash.now[:alert] = "Question didn't save!"
      render :edit
    end
  end

  def destroy
    @question.destroy
    redirect_to questions_path, notice: "Question: #{@question.title} deleted!"
  end

private

  def authorize_question
    redirect_to root_path unless can? :crud, @question
  end

  def find_question
    @question = Question.friendly.find params[:id]
  end

  def question_params
    params.require(:question).permit([:title, :body, :image, :category_id, {tag_ids: []}])
  end

  # def user_like
  #     @user_like ||= @question.like_for(current_user)
  # end
  # helper_method :user_like


end

app/helpers/admin/questions_helper.rb
module Admin::QuestionsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper

  def user_like
      @user_like ||= @question.like_for(current_user)
  end

end

app/views/questions/_form.html.erb
<%# This file is considered to be a partial which means you can include it in any other template (like new or edit), you must start the partial name with _ . Partials have access to the same instance variables available in the templates (e.g. @question) %>

<%= @question.errors.full_messages.join(". ") %>
<br>
<br>


<%# form_for is a Rails helper method %>
<div class="row">
  <div class="col-lg-6 col-md-6 col-sm-8 col-xs-12">
      <%= simple_form_for @question do |f| %>
      <%# if @question is not persisted in the database. form_for makes the 'action' of the form go to 'questions_path' and it will make the method of form to be POST%>
        <div>
          <%= f.input :title %>
          <%= f.input :body %>
          <%= f.association :category %>
          <%= f.association :tags, input_html: {class: "chosen-select"} %>
          <%= f.input :image %>
          <%# Byusing f.text_field :title, if @question has a value for the attribute 'title' it will populate the field with that value. This is usually the case when redisplaying the form after an error occurs %>
        <!-- <div> -->
          <%# f.label :category %>
          <%# f.collection_select :category_id, Category.order(:name), :id, :name, {prompt: "Select a category"}, {class: "form-control"} %>
        <!-- </div> -->
      <br>
        <!-- <div style="display: inline-block; margin-bottom: 10px"> -->
          <%# f.label :tag_ids, "Tags" %>
          <!-- <br> -->
          <%# f.collection_check_boxes :tag_ids, Tag.order(:name), :id, :name do |c| %>
            <!-- <span class="checkbox-s col-md-4 col-sm-4 col-xs-6"> -->
              <%# c.label { c.check_box + c.text } %>
            <!-- </span> -->
          <%# end %>
        </div>
          <div>
            <%= f.submit class:"btn btn-success btn-lg"%>
          </div>

      <% end %>
  </div>
</div>

app/views/questions/_likesform.html.erb
<% if user_like %>
  <%= link_to question_like_path(@question, user_like), method: :delete do %>
  <span class="glyphicon glyphicon-heart" style="font-size:1.5em"></span>
  <% end %>
<% else %>
  <%= link_to question_likes_path(@question), method: :post do %>
    <span class="glyphicon glyphicon-heart-empty" style="font-size:1.5em"></span>
    <% end %>
<% end %>

app/views/questions/_votesform.html.erb
<% user_vote = @question.vote_for(current_user) %>
<% if user_vote && user_vote.is_up? %>
  <%= link_to question_vote_path(@question, user_vote), method: :delete do %>
  <span class="glyphicon glyphicon-hand-right" style="color: red; font-size:1.5em"></span>&nbsp;&nbsp;
  <% end %>
  <%= link_to question_vote_path(@question, user_vote, {vote: {is_up: false}}), method: :patch do %>
  <span class="glyphicon glyphicon-thumbs-down" style="font-size:1.5em"></span>
  <% end %>
<% elsif user_vote %>
  <%= link_to question_vote_path(@question, user_vote, {vote: {is_up: false}}), method: :patch do %>
  <span class="glyphicon glyphicon-thumbs-up" style="font-size:1.5em"></span>&nbsp;&nbsp;
  <% end %>
  <%= link_to question_vote_path(@question, user_vote), method: :delete do %>
  <span class="glyphicon glyphicon-hand-right" style="color: red; font-size:1.5em"></span>
  <% end %>
<% else %>
  <%= link_to question_votes_path(@question, {vote: {is_up: true}}), method: :post do %>
  <span class="glyphicon glyphicon-thumbs-up" style="font-size:1.5em"></span>&nbsp;&nbsp;
  <% end %>
  <%= link_to question_votes_path(@question, {vote:{is_up: false}}), method: :post do %>
  <span class="glyphicon glyphicon-thumbs-down" style="font-size:1.5em"></span>
  <% end %>
<% end %>

app/views/questions/edit.html.erb
<h1>Edit Question</h1>

<%= render "form" %>

app/views/questions/index.html.erb
<h1>All Questions</h1>
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Question Title</th>
        <th>Creator</th>
        <th>Likes</th>
        <th>Votes</th>
      </tr>
    </thead>
  <% @questions.each do |q| %>
    <tbody>
      <tr>
        <td>    <%= link_to question_path(q) do %>
          <%= q.title %>
      <% if q.image.present? %>
        <%= image_tag q.image.url(:thumb) %>
      <% end %>
    <% end %></td>
        <td><%= q.user_full_name %></td>
        <td><%= q.likes.count %></td>
        <td><%= q.vote_value %></td>
      </tr>
    </tbody>
    <% end %>
  </table>

app/views/questions/new.html.erb
<h1>New Question</h1>
<%= render "form" %>

app/views/questions/show.html.erb
<div class="row questionbox">
  <div class="row questionbox-margins">

    <span class="h4">
      <span class="tag-tooltip pull-right label label-danger" data-toggle="tooltip" data-placement="bottom" title="Liked by: <%= @list_of_liked_users  %>"><span class="glyphicon glyphicon-heart" aria-hidden="true"></span> Likes <span class="badge"><%= @question.likes.count %></span></span>
      <span class="tag-tooltip pull-right label label-danger" style="margin-right:10px" data-toggle="tooltip" data-placement="bottom" title="Voters: <%= @list_of_voting_users  %>"><span class="glyphicon glyphicon-bullhorn" aria-hidden="true"></span> Total Votes <span class="badge"><%= @question.vote_value %></span></span>
    </span>

    <span class="h1">
      <%= @question.title %>
    </span>
    <p>Created by: <%= @question.user_full_name.titleize %></p>
  </div>
  <div class="col-lg-10 col-md-8 col-sm-10 col-xs-12">
    <p class="question-body"><%= @question.body %> </p>
    <p style="font-size: 1.2em">View Count: <%= @question.view_count %></p>

    <span>Tags: <% @question.tags.each do |t| %>
      <div class='label label-primary'><%= t.name %></div>
    </span>
    <% end %>

    <% if @question.image.present? %>
    <%= image_tag @question.image.url, class: "full-width" %>
    <% end %>

    <br>
    <br>
    <%# can? is a helper method that came from the CanCanCan gem to help us enforce authorization rules in the views and controllers. We didn't specifically put rules for :edit and :destroy but we put a rule for :crud which includes both of them %>
    <% if can? :edit, @question %>
    <%= link_to "EDIT", edit_question_path(@question), class: 'btn btn-info btn-xs' %>
    <% end %>
    &nbsp;
    <% if can? :destroy, @question %>
    <%= link_to "DELETE", question_path(@question),
                          method: :delete,
                          data: {confirm: "Are you dead on sure you want to do this?"},
                          class: 'btn btn-info btn-xs' %>
    <% end %>
    &nbsp;




  <div id="question-like">
    <%= render "/likes/like" %>
  </div>
   <%= render "/questions/votesform" %>

    <hr>

    <h2>Answers</h2>
    <div id="answers">
      <% @question.answers.each do |ans| %>
        <%= render "/answers/answer", answer: ans %>
    <% end %>
  </div>

    <h2>Add An Answer</h2>
    <div id="answer-form">
      <%= render "/answers/form", answer: @answer %>
    </div>

  </div>



<!-- Modal -->
<div class="modal fade" id="edit-answer" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">

</div>


</div>