config/routes.rb
Rails.application.routes.draw do

match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

resources :password_resets, only: [:new, :create, :edit, :update]

  get "/home" => "welcome#index"

  get "/about" => "welcome#about", as: :about_us

  root "welcome#index"

  get "/contact_us" => "contact_us#new"
  post "/contact_us" => "contact_us#create"

  resources :users, only: [:new, :create]

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  resources :questions do

    resources :answers, only: [:create, :destroy, :edit, :update]
    resources :likes, only: [:create, :destroy]
    resources :votes, only: [:create, :update, :destroy]
    resources :insights, only: [:create]
  end

get "/questions" => "questions#index"

end

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-default navbar-fixed-top navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">AA</a>
    </div>

    <div class="collapse navbar-collapse" id="navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="<%= 'active' if current_page?(about_us_path) %>"><%= link_to "About Us", about_us_path %></li>
        <li class="<%= 'active' if current_page?(contact_us_path) %>"><%= link_to "Contact Us", contact_us_path %> </li>
        <li class="<%= 'active' if current_page?(questions_path) %>"><%= link_to "Questions", questions_path %> </li>
        <li class="<%= 'active' if current_page?(new_question_path) %>"><%= link_to "New Question", new_question_path %> </li>

      </ul>
      <div class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="navbar-text">Hello <%= current_user.first_name %></li>
          <li><%= link_to "Logout", sessions_path, method: :delete,
                        data: {confirm: "are you sure you want to log out?"}%></li>
        <% else %>
        <li class="<%= 'active' if current_page?(new_session_path) %>"><%= link_to "Login", new_session_path %></li>
        <li class="<%= 'active' if current_page?(new_user_path) %>"><%= link_to "Sign Up", new_user_path %></li>
        <% end %>
      </div>



    </div>
  </div>
</nav>