config/routes.rb
Rails.application.routes.draw do

match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

resources :password_resets, only: [:new, :create, :edit, :update]

  get "/home" => "welcome#index"

  get "/about" => "welcome#about", as: :about_us

  root "welcome#index"

  get "/contact_us" => "contact_us#new"
  post "/contact_us" => "contact_us#create"

  resources :users, only: [:new, :create]

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  resources :questions do

    resources :answers, only: [:create, :destroy, :edit, :update]
    resources :likes, only: [:create, :destroy]
    resources :votes, only: [:create, :update, :destroy]
    resources :insights, only: [:create]
  end

get "/questions" => "questions#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AwesomeAnswers</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<!-- <a href="<%= home_path %>">Home</a>
|
<a href="<%= about_us_path %>">About</a>
| -->
<!-- The link_to helper method that comes from Rails which generated an <a> HTML element. It takes two primary arguments. The first is for the anchor texto and the second argument is for the "href" value (where you want to link to) -->

<%= render 'shared/navigation' %>

<%# flash[:notice] || flash[:alert] %>

<div id="main-container" class="container">
      <div class="row">
        <div class="col-lg-12">
            <%# flash.each do |key, value| %>
                <%# content_tag :div, class: "alert alert-#{['success','danger'].include?(key) ? 'success' : 'danger'}" do %>
                  <!-- <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button> -->
                <%# value %>
              <%# end %>
            <%# end %>
            <% flash.each do |key, value| %>
              <div id="flashmsg" class="alert alert-<%= key %> alert-dismissible">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <%= value %>
              </div>
            <% end %>
          <%= yield %>
        </div>
      </div>
    </div>

</body>
</html>

app/views/layouts/special.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Welcome to Awesome Answers</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <!-- <a href="<%= home_path %>">Home</a> -->
  <%# link_to is a helper method that comes from Rails which generates an <a>
      HTML element. The `link_to` method takes two primary arguments. The first
      argument is for the anchor text and the second argument is for the `href`
      value (where you want to link to) %>
  <%= link_to("Home", home_path, {class: "abc"}) %>
  |
  <!-- <a href="<%= about_us_path %>">About</a> -->
  <%= link_to "About", about_us_path({a: 'hello', b: 123}) %>
  |
  <%= link_to "Contact Us", contact_us_path %>
  |
  <%= link_to "New Question", new_question_path %>

  <hr>
  <h1>Special Layout</h1>
  <%= yield %>

</body>
</html>